### ISSUE TITLE
Pinbelegung

### ISSUE THREAD

**Issue by AsdOmega** [rudeldi/p2.arduino#22]
Hi,

bei der Pinbelegung gibt es eine Diskrepantz zwischen Excel-File und Programm

Programm
int red1 =  15;
int red2 =  16;
int red3 =  17;
int red4 =  18;

int green1 =  19;
int green2 =  20;
int green3 =  21;
int green4 =  22;

Excel
D15	x	LED red 1
D16	x	LED green 1
D17	x	LED red 2
D18	x	LED green 2
D19	x	LED red 3
D20	x	LED green 3
D21	x	LED red 4
D22	x	LED green 4

**Comment by rudeldi** [comment]
Danke! Werd ich mir gleich mal ändern

**Comment by rudeldi** [comment]
@AsdOmega, vielen Dank, habe ich ausgebessert, irgendwie untergegangen beim bauen des Projekts
